package main;

public class TestClass {

	public void method01() {
		System.out.println("method01 start !");
		method02();
		System.out.println("method01 end ...");
	}
	
	public void method02() {
		System.out.println("method02 start !");
		try {
//			throw new Exception("zzz");
			throw new KhException();
		}catch(Exception e) {
			System.out.println("예외 발생");
			System.out.println(e.getMessage());
		}
		method03();
		System.out.println("method02 end ... !");
	}
	
	public void method_02() {
		System.out.println("method02 start !");
		try {
			//예외 발생 의심 코드
			System.out.println("1111");
			int x = 1 / 1 ;
			System.out.println("2222");
		}catch(Exception e) { //잡으려는 예외 타입 (Exception은 모든 예외를 잡는 것)
			//예외를 잡은 후 실행할 내용을 출력문으로 작성
			System.out.println("예외 발생");
//			System.out.println(e);
//			System.out.println(e.getMessage());
//			e.printStackTrace(); // 그동안 쌓여있던 에러관련 정보들을 전부 출력
		}finally {  //try블록 마지막에 finally를 추가하면 무조건 실행됨 (try 뒤에만 있으면 됨)
			System.out.println("파이널리 블록");
		}
		
		method03();
		System.out.println("method02 end ...");
	}
	public void method03() {
		System.out.println("method03 start !");
		System.out.println("method03 end ...");
	}
	
	
	
	
	
	
} //class
